[profile.default]
src = "src"
out = "out"
script = "scripts"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
#  " @openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[profile.main]
solc = "0.8.25"
evm_version = "cancun"

[profile.types]
solc = "0.8.17"
via_ir = true
